redis:
  address: "localhost:6379"
  password: ""
  db: 0

subscriptions:
  binance:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - XRPUSDT
  - ADAUSDT
  - DOGEUSDT
  - MATICUSDT
  - SOLUSDT
  - ETHBTC
  kucoin:
  - BTC-USDT
  - ETH-USDT
  - BNB-USDT
  - XRP-USDT
  - ADA-USDT
  - DOGE-USDT
  - MATIC-USDT
  - SOL-USDT
  - ETH-BTC