redis:
  address: "localhost:6379"
  password: ""
  db: 0

subscriptions:
  binance:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - XRPUSDT
  - ADAUSDT
  - DOGEUSDT
  - MATICUSDT
  - SOLUSDT
  - DOTUSDT
  - TRXUSDT
  - SHIBUSDT
  - LTCUSDT
  - AVAXUSDT
  - ETHBTC
  - BNBBTC
  - XRPBTC
  - ADABTC
  - DOGEBTC
  - MATICBTC
  - SOLBTC
  - DOTBTC
  - TRXBTC
  - LTCBTC
  - AVAXBTC

  kucoin:
  - BTC-USDT
  - ETH-USDT
  - BNB-USDT
  - XRP-USDT
  - ADA-USDT
  - DOGE-USDT
  - MATIC-USDT
  - SOL-USDT
  - DOT-USDT
  - TRX-USDT
  - SHIB-USDT
  - LTC-USDT
  - AVAX-USDT
  - ETH-BTC
  - BNB-BTC
  - XRP-BTC
  - ADA-BTC
  - DOGE-BTC
  - MATIC-BTC
  - SOL-BTC
  - DOT-BTC
  - TRX-BTC
  - LTC-BTC
  - AVAX-BTC